apiVersion: v2
name: ebrowser
description: eBrowser v2.0 — The Most Secure Lightweight Browser
type: application
version: 2.0.0
appVersion: "2.0.0"
maintainers:
  - name: embeddedos-org
    url: https://github.com/embeddedos-org
keywords:
  - browser
  - security
  - lightweight
  - embedded
  - iot
  - privacy
home: https://github.com/embeddedos-org/eBrowser
sources:
  - https://github.com/embeddedos-org/eBrowser
